### ISSUE TITLE
Security issue in handlebars version

### ISSUE THREAD

**Issue by tiagojsag** [tandrewnichols/grunt-simple-nyc#2]
The `handlebars` version on the current master has a known security issue: https://www.npmjs.com/advisories/755

**Comment by tandrewnichols** [comment]
I'm not using handlebars?

`npm ls handlebars` says it's included via `nyc` itself for generating coverage reports. This is a dev tool for coverage so it seems unlikely to be a problem unless you're executing an attack against your own code or hosting your coverage reports publicly (and even then, they're generated statically with no running server behind them).

I'll create a branch that updates `nyc` to the latest release, but here's the deal: I don't believe this is a real issue for this module, but updating `nyc` may very well cause other problems (I haven't looked at the change log, but it's a major update, so there are potentially breaking changes). If you're really invested in this, please pull that branch and use it and confirm that it doesn't break stuff.

**Comment by tandrewnichols** [comment]
New branch is called `nyc@13.3.0`.

To be clear, I will _eventually_ get to testing this myself, but it's not a high priority, so if you believe this is important, you could help me out by trying that branch.

Thanks.

**Comment by tiagojsag** [comment]
Hi,

Yes, I fully agree that this is not a major flaw, as probably no one is using this in a prod environment, like you said.

I'll start using that branch, see if I find anything during my normal usage, and report back if I find anything.

BTW thanks for taking the time to create and maintain this OSS project :+1:

**Comment by tandrewnichols** [comment]
Great! Thanks again.

**Comment by tandrewnichols** [comment]
Just published version 2.0.0 which updates the nyc dependency.
