### ISSUE TITLE
Preserving colors from nyc output

### ISSUE THREAD

**Issue by vamship** [tandrewnichols/grunt-simple-nyc#4]
I'm using the plugin for code coverage on server side unit tests, and it works great.

It would be really nice if the plugin could preserve the color of the output from nyc/mocha. In looking through the code, it appears that this support must be added to the simple-cli library.

I was able to get this to work by updating builder.js in simple-cli with the following changes:
1. Add `stdio: 'inherit',` to line 194
2. Comment out lines 202 - 216

This enables colors, but does not include any output for the onComplete callback. I can submit a PR if necessary.

Thoughts?

**Comment by tandrewnichols** [comment]
I can't remember, but I _believe_ there was a reason I chose not to use "inherit." Maybe it was just the onComplete . . . that was a long time ago. At any rate, probably adding FORCE_COLOR=1 to env for that spawned process would also work.

**Comment by vamship** [comment]
Yeah, I running mocha with --colors solved the problem for me. Thanks for the quick response. Much appreciated.

**Comment by tandrewnichols** [comment]
No problem. I'm not convinced that _keeping_ `onComplete` is the right thing. It seems less useful now than I think I imagined it being at one time. But I'll put that decision off for now.
